version: '3'
services:
  elasticsearch:
    build:
      context: ./elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    build:
      context: ./logstash
    ports:
      - "5400:5400"
      - "9600:9600"
    depends_on:
      - "elasticsearch"
  kibana:
    build:
      context: ./kibana
    ports:
      - "5601:5601"
    depends_on:
      - "elasticsearch"
